# Generated by Django 4.0.5 on 2022-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0002_alter_userprofile_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='image/'),
        ),
    ]
